apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-crbc
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  verbs:
  - get
  - list
  - update
  - patch
  - create
- apiGroups:
    - ""
  resources:
    - serviceaccounts
  verbs:
    - get
    - list
- apiGroups:
    - rbac.authorization.k8s.io
  resources:
    - clusterroles
  verbs:
    - get
    - list
- apiGroups:
    - ""
  resources:
    - namespaces
  verbs:
    - get
    - list